[build]
  publish = "."  # Root directory, so it includes root-level index.html

[[redirects]]
  from = "/chat.html"
  to = "/frontend/chat.html"
  status = 200

[[redirects]]
  from = "/login.html"
  to = "/frontend/login.html"
  status = 200

[[redirects]]
  from = "/register.html"
  to = "/frontend/register.html"
  status = 200

[[redirects]]
  from = "/faq.html"
  to = "/frontend/pages/faq.html"
  status = 200

[[redirects]]
  from = "/support.html"
  to = "/frontend/pages/support.html"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/frontend/js/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/frontend/css/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/frontend/assets/:splat"
  status = 200

[[redirects]]
  from = "/translations/*"
  to = "/frontend/translations/:splat"
  status = 200

[[redirects]]
  from = "/firebase-init.js"
  to = "/frontend/firebase-init.js"
  status = 200

# Catch-all fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
