[build]
  publish = "."  # Root directory, index.html lives here

# === Page Redirects ===

[[redirects]]
  from = "/chat.html"
  to = "/frontend/chat.html"
  status = 200

[[redirects]]
  from = "/login.html"
  to = "/frontend/login.html"
  status = 200

[[redirects]]
  from = "/register.html"
  to = "/frontend/register.html"
  status = 200

[[redirects]]
  from = "/faq.html"
  to = "/frontend/pages/faq.html"
  status = 200

[[redirects]]
  from = "/support.html"
  to = "/frontend/pages/support.html"
  status = 200

# === Static Assets Routing ===

[[redirects]]
  from = "/js/*"
  to = "/frontend/js/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/frontend/css/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/frontend/assets/:splat"
  status = 200

[[redirects]]
  from = "/translations/*"
  to = "/frontend/translations/:splat"
  status = 200

[[redirects]]
  from = "/firebase-init.js"
  to = "/frontend/firebase-init.js"
  status = 200

# === MIME Type Fix for Firebase ===

[[headers]]
  for = "/frontend/firebase-init.js"
  [headers.values]
    Content-Type = "application/javascript"

# === Catch-All Root Redirect ===

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
