[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/chat.html"
  to = "/chat.html"
  status = 200

[[redirects]]
  from = "/login.html"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/register.html"
  to = "/register.html"
  status = 200

[[redirects]]
  from = "/pages/faq.html"
  to = "/pages/faq.html"
  status = 200

[[redirects]]
  from = "/pages/support.html"
  to = "/pages/support.html"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/translations/*"
  to = "/translations/:splat"
  status = 200

[[redirects]]
  from = "/firebase-init.js"
  to = "/firebase-init.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
