[build]
  publish = "frontend"

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/chat"
  to = "/chat.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/preferences"
  to = "/preferences.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
