[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/chat.html"
  to = "/chat.html"
  status = 200
  force = true

[[redirects]]
  from = "/login.html"
  to = "/frontend/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/register.html"
  to = "/frontend/register.html"
  status = 200
  force = true

[[redirects]]
  from = "/assets/*"
  to = "/frontend/assets/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/frontend/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/frontend/js/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
